exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    enabled: false
  FeatureEnvy:
    exclude:
      - HTMX::Configuration::Builder#dump
  ModuleInitialize:
    exclude:
      - HTMX::Headers
  NilCheck:
    exclude:
      - HTMX::Configuration::Builder#format_with
